dist: trusty
sudo: false
language: ruby
rvm:
  - 2.4.0
services:
  - postgresql
addons:
  postgresql: "9.6"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.travis.yml config/database.yml
